checks:
  golint:
    filters:
      - value: "should have comment or be unexported"
      - value: "or a comment on this block"
  ineffassign:
    filters:
      - value: "ineffectual assignment to unit"
  errcheck:
    filters:
      - value: "nolint: errcheck"
