products:
  pgx_exporter:
    build:
      main-pkg: cmd/pgx_exporter
      os-archs:
        - os: darwin
          arch: amd64
        - os: linux
          arch: amd64
    dist:
      disters:
        type: os-arch-bin
        config:
          os-archs:
            - os: darwin
              arch: amd64
            - os: linux
              arch: amd64
    docker:
      repository: oscarmherrera
      docker-builders:
        pgx_exporter:
          type: default
          context-dir: .
          input-products-dir: inputs
          tag-templates:
            - "{{Repository}}pgx_exporter:{{Version}}"
            - "{{Repository}}pgx_exporter:latest"